# Generated by Django 3.2.8 on 2021-11-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irjp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='signature',
        ),
    ]
