# Generated by Django 3.2.8 on 2021-11-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irjp', '0002_remove_registration_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('nostreet', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('telno', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=100)),
                ('birthplace', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('civilstatus', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
    ]
